src/Entity/Master/Paper.php
<?php

namespace App\Entity\Master;

use App\Entity\Master;
use App\Repository\Master\PaperRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PaperRepository::class)]
#[ORM\Table(name: 'master_paper')]
#[UniqueEntity(['name'])]
class Paper extends Master
{
    public const PRICING_MODE_ASSOCIATION = 'association';
    public const PRICING_MODE_WEIGHT = 'weight';
    public const PRICING_MODE_UNIT = 'unit';
    public const TYPE_FSC = 'fsc';
    public const TYPE_NON_FSC = 'non';
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\GreaterThanOrEqual(0)]
    private ?string $length = '0';

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull]
    #[Assert\GreaterThanOrEqual(0)]
    private ?string $width = '0';

    #[ORM\ManyToOne(inversedBy: 'papers')]
    #[Assert\NotNull]
    private ?Unit $unit = null;

    #[ORM\Column(length: 60)]
    private ?string $pricingMode = '';

    #[ORM\Column(length: 60)]
    private ?string $type = '';

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotNull]
    private ?string $note = '';

    #[ORM\ManyToOne(inversedBy: 'papers')]
    #[Assert\NotNull]
    private ?MaterialSubCategory $materialSubCategory = null;

    #[ORM\Column(length: 60)]
    private ?string $weight = '';

    #[ORM\OneToMany(mappedBy: 'paper', targetEntity: DesignCode::class)]
    private Collection $designCodes;

    #[ORM\Column]
    private ?int $code = 0;

    public function __construct()
    {
        $this->designCodes = new ArrayCollection();
    }

    public function getPaperNameSizeCombination(): string
    {
        return $this->name . ' ' . $this->weight . '-' . $this->length . '-' . $this->width;
    }
    
    public function getCodeNumber(): string
    {
        $type = ($this->type === self::TYPE_FSC) ? 'FSC' : '000';
        
        return $this->materialSubCategory === null ? '---' : sprintf('%s-%s-%s-%03d', $this->materialSubCategory->getCode(), $this->weight, $type, $this->code);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLength(): ?string
    {
        return $this->length;
    }

    public function setLength(string $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getWidth(): ?string
    {
        return $this->width;
    }

    public function setWidth(string $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getUnit(): ?Unit
    {
        return $this->unit;
    }

    public function setUnit(?Unit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getPricingMode(): ?string
    {
        return $this->pricingMode;
    }

    public function setPricingMode(string $pricingMode): self
    {
        $this->pricingMode = $pricingMode;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setPaper($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getPaper() === $this) {
                $product->setPaper(null);
            }
        }

        return $this;
    }

    public function getMaterialSubCategory(): ?MaterialSubCategory
    {
        return $this->materialSubCategory;
    }

    public function setMaterialSubCategory(?MaterialSubCategory $materialSubCategory): self
    {
        $this->materialSubCategory = $materialSubCategory;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->weight;
    }

    public function setWeight(string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * @return Collection<int, DesignCode>
     */
    public function getDesignCodes(): Collection
    {
        return $this->designCodes;
    }

    public function addDesignCode(DesignCode $designCode): self
    {
        if (!$this->designCodes->contains($designCode)) {
            $this->designCodes->add($designCode);
            $designCode->setPaper($this);
        }

        return $this;
    }

    public function removeDesignCode(DesignCode $designCode): self
    {
        if ($this->designCodes->removeElement($designCode)) {
            // set the owning side to null (unless already changed)
            if ($designCode->getPaper() === $this) {
                $designCode->setPaper(null);
            }
        }

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }
}

src/Controller/Report/AccountingLedgerController.php
<?php

namespace App\Controller\Report;

use App\Common\Data\Criteria\DataCriteria;
use App\Common\Data\Operator\FilterBetween;
use App\Entity\Accounting\AccountingLedger;
use App\Grid\Report\AccountingLedgerGridType;
use App\Repository\Accounting\AccountingLedgerRepository;
use App\Repository\Master\AccountRepository;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Reader\Html;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/report/accounting_ledger')]
class AccountingLedgerController extends AbstractController
{
    #[Route('/_list', name: 'app_report_accounting_ledger__list', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FINANCE_REPORT')]
    public function _list(Request $request, AccountRepository $accountRepository, AccountingLedgerRepository $accountingLedgerRepository): Response
    {
        $criteria = new DataCriteria();
        $currentDate = date('Y-m-d');
        $criteria->setFilter([
            'accountingLedger:transactionDate' => [FilterBetween::class, $currentDate, $currentDate],
        ]);
        $form = $this->createForm(AccountingLedgerGridType::class, $criteria);
        $form->handleRequest($request);

        list($count, $accounts) = $accountRepository->fetchData($criteria, function($qb, $alias) use ($criteria) {
            $qb->andWhere("{$alias}.isInactive = false");
            $qb->andWhere("EXISTS (SELECT l.id FROM " . AccountingLedger::class . " l WHERE {$alias} = l.account AND l.isReversed = false AND l.transactionDate BETWEEN :startDate AND :endDate)");
            $qb->setParameter('startDate', $criteria->getFilter()['accountingLedger:transactionDate'][1]);
            $qb->setParameter('endDate', $criteria->getFilter()['accountingLedger:transactionDate'][2]);
            $qb->addOrderBy("{$alias}.name", 'ASC');
        });
        $beginningBalanceList = $this->getBeginningBalanceList($accountingLedgerRepository, $criteria, $accounts);
        $accountingLedgers = $this->getAccountingLedgers($accountingLedgerRepository, $criteria, $accounts);

        if ($request->request->has('export')) {
            return $this->export($form, $accounts, $beginningBalanceList, $accountingLedgers);
        } else {
            return $this->renderForm("report/accounting_ledger/_list.html.twig", [
                'form' => $form,
                'count' => $count,
                'accounts' => $accounts,
                'beginningBalanceList' => $beginningBalanceList,
                'accountingLedgers' => $accountingLedgers,
            ]);
        }
    }

    #[Route('/', name: 'app_report_accounting_ledger_index', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FINANCE_REPORT')]
    public function index(): Response
    {
        return $this->render("report/accounting_ledger/index.html.twig");
    }

    private function getBeginningBalanceList(AccountingLedgerRepository $accountingLedgerRepository, DataCriteria $criteria, array $accounts): array
    {
        $startDate = $criteria->getFilter()['accountingLedger:transactionDate'][1];
        $accountBeginningBalanceList = $accountingLedgerRepository->getAccountBeginningBalanceList($accounts, $startDate);
        $beginningBalanceList = [];
        foreach ($accountBeginningBalanceList as $accountBeginningBalanceItem) {
            $beginningBalanceList[$accountBeginningBalanceItem['accountId']] = $accountBeginningBalanceItem['beginningBalance'];
        }

        return $beginningBalanceList;
    }

    private function getAccountingLedgers(AccountingLedgerRepository $accountingLedgerRepository, DataCriteria $criteria, array $accounts): array
    {
        $startDate = $criteria->getFilter()['accountingLedger:transactionDate'][1];
        $endDate = $criteria->getFilter()['accountingLedger:transactionDate'][2];
        $accountingLedgers = $accountingLedgerRepository->findAccountingLedgers($accounts, $startDate, $endDate);
        $journalLedgers = [];
        foreach ($accountingLedgers as $accountingLedger) {
            $journalLedgers[$accountingLedger->getAccount()->getId()][] = $accountingLedger;
        }

        return $journalLedgers;
    }

    public function export(FormInterface $form, array $accounts, array $beginningBalanceList, array $accountingLedgers): Response
    {
        $htmlString = $this->renderView("report/accounting_ledger/_list_export.html.twig", [
            'form' => $form->createView(),
            'accounts' => $accounts,
            'beginningBalanceList' => $beginningBalanceList,
            'accountingLedgers' => $accountingLedgers,
        ]);

        $reader = new Html();
        $spreadsheet = $reader->loadFromString($htmlString);

        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $response =  new StreamedResponse(function() use ($writer) {
            $writer->save('php://output');
        });

        $filename = 'accounting_ledger.xlsx';
        $dispositionHeader = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, $filename);
        $response->headers->set('Content-Type', 'application/vnd.ms-excel');
        $response->headers->set('Content-Disposition', $dispositionHeader);

        return $response;
    }
}

src/Controller/Report/AdjustmentStockHeaderController.php
<?php

namespace App\Controller\Report;

use App\Common\Data\Criteria\DataCriteria;
use App\Common\Data\Operator\FilterBetween;
use App\Grid\Report\AdjustmentStockHeaderGridType;
use App\Repository\Stock\AdjustmentStockHeaderRepository;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Reader\Html;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/report/adjustment_stock_header')]
class AdjustmentStockHeaderController extends AbstractController
{
    #[Route('/_list', name: 'app_report_adjustment_stock_header__list', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_INVENTORY_MATERIAL_REPORT')]
    public function _list(Request $request, AdjustmentStockHeaderRepository $adjustmentStockHeaderRepository): Response
    {
        $criteria = new DataCriteria();
        $currentDate = date('Y-m-d');
        $criteria->setFilter([
            'transactionDate' => [FilterBetween::class, $currentDate, $currentDate],
        ]);
        $form = $this->createForm(AdjustmentStockHeaderGridType::class, $criteria);
        $form->handleRequest($request);

        list($count, $adjustmentStockHeaders) = $adjustmentStockHeaderRepository->fetchData($criteria, function($qb, $alias, $add) use ($request) {
            if (isset($request->request->get('adjustment_stock_header_grid')['filter']['supplier:company']) && isset($request->request->get('adjustment_stock_header_grid')['sort']['supplier:company'])) {
                $qb->innerJoin("{$alias}.supplier", 's');
                $add['filter']($qb, 's', 'company', $request->request->get('adjustment_stock_header_grid')['filter']['supplier:company']);
                $add['sort']($qb, 's', 'company', $request->request->get('adjustment_stock_header_grid')['sort']['supplier:company']);
            }
        });

        if ($request->request->has('export')) {
            return $this->export($form, $adjustmentStockHeaders);
        } else {
            return $this->renderForm("report/adjustment_stock_header/_list.html.twig", [
                'form' => $form,
                'count' => $count,
                'adjustmentStockHeaders' => $adjustmentStockHeaders,
            ]);
        }
    }

    #[Route('/', name: 'app_report_adjustment_stock_header_index', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_INVENTORY_MATERIAL_REPORT')]
    public function index(): Response
    {
        return $this->render("report/adjustment_stock_header/index.html.twig");
    }

    public function export(FormInterface $form, array $adjustmentStockHeaders): Response
    {
        $htmlString = $this->renderView("report/adjustment_stock_header/_list_export.html.twig", [
            'form' => $form->createView(),
            'adjustmentStockHeaders' => $adjustmentStockHeaders,
        ]);

        $reader = new Html();
        $spreadsheet = $reader->loadFromString($htmlString);

        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $response =  new StreamedResponse(function() use ($writer) {
            $writer->save('php://output');
        });

        $filename = 'penyesuaian stok.xlsx';
        $dispositionHeader = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, $filename);
        $response->headers->set('Content-Type', 'application/vnd.ms-excel');
        $response->headers->set('Content-Disposition', $dispositionHeader);

        return $response;
    }
}

templates/report/adjustment_stock_header/_list.html.twig
{% import 'app/data_grid.html.twig' as grid %}

<div class="d-print-none">
    {{ grid.form(form) }}

    <div class="my-3 px-3 bg-light" {{ grid.filter_link(form) }}>
        <div class="row">
            <div class="col">
                <div class="my-2 row">
                    <label class="col-sm-2 col-form-label w-25">Transaction Date</label>
                    <div class="col-sm-10 w-75">
                        <div class="row">
                            <div class="col">
                                <input class="form-control readonly-form-input" type="text" data-controller="flatpickr-element" {{ grid.filter_link_item(form, 'transactionDate', [form.filter['transactionDate'].0.vars.choices.0.value, true, false]) }} value="{{ form.filter.transactionDate.1.vars.value }}" />
                            </div>
                            <div class="col">
                                <input class="form-control readonly-form-input" type="text" data-controller="flatpickr-element" {{ grid.filter_link_item(form, 'transactionDate', [form.filter['transactionDate'].0.vars.choices.0.value, false, true]) }} value="{{ form.filter.transactionDate.2.vars.value }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="my-2 row">
                    <label class="col-sm-2 col-form-label w-25">Code Number</label>
                    <div class="col-sm-10 w-75">
                        <input style="width: 64px" type="number" {{ grid.filter_link_item(form, 'codeNumberOrdinal') }} value="{{ form.filter.codeNumberOrdinal.1.vars.value }}" />
                        <span><small>/{{ constant('App\\Entity\\Stock\\AdjustmentStockHeader::CODE_NUMBER_CONSTANT') }}/</small></span>
                        <select {{ grid.filter_link_item(form, 'codeNumberMonth') }}>
                            {% for value, label in constant('App\\Entity\\PurchaseHeader::MONTH_ROMAN_NUMERALS') %}
                                {% set val = value == 0 ? '' : value %}
                                <option value="{{ val }}" {% if form.filter.codeNumberMonth.1.vars.value == val %}selected="selected"{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                        <span><small>/</small></span>
                        <input style="width: 64px" type="number" {{ grid.filter_link_item(form, 'codeNumberYear') }} value="{{ form.filter.codeNumberYear.1.vars.value }}" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="d-grid">
        <div class="row">
            <div class="col text-center">
                <button type="submit" class="btn btn-primary btn-sm"
                        data-controller="redirection"
                        data-redirection-url-value="{{ path('app_report_adjustment_stock_header__list') }}"
                        data-redirection-form-target-value="form[name={{ form.vars.name }}]"
                        data-redirection-extra-values-param="{{ {export: 'export'}|json_encode }}"
                        data-action="redirection#redirect">
                    Export
                </button>
            </div>
        </div>
    </div>

    {{ grid.info(form, count, adjustmentStockHeaders) }}

    <hr />
</div>

<div class="report">
    <div class="report-header">
        <div class="report-title">PT. Putracipta Karindomas</div>
        <div class="report-title">Laporan Penyesuaian Stok</div>
        <div>
            {% set startDate = form.vars.value.filter.transactionDate.1|default %}
            {% set endDate = form.vars.value.filter.transactionDate.2|default %}
            {{ startDate ? startDate|date('j F Y') }} &nbsp;&ndash;&nbsp; {{ endDate ? endDate|date('j F Y') }}
        </div>
    </div>

    <br />

    <table class="report-data">
        <thead class="border-top-solid-bold border-bottom-solid-bold">
            <tr>
                <th class="text-start">Penyesuaian #</th>
                <th class="text-start">Tanggal</th>
                <th class="text-start">Jenis</th>
                <th class="text-start">Gudang</th>
                <th class="text-start">Note</th>
            </tr>
            <tr>
                <td colspan="5">
                    <table>
                        <thead>
                            <tr>
                                <th class="text-start">Kode</th>
                                <th class="text-start">Nama Item</th>
                                <th class="text-start">Qty Stok</th>
                                <th class="text-start">Qty Adjustment</th>
                                <th class="text-start">Qty Selisih</th>
                                <th class="text-start">Satuan</th>
                                <th class="text-start">Memo</th>
                            </tr>
                        </thead>
                    </table>
                </td>
            </tr>
        </thead>
        <tbody class="border-top-solid-bold border-bottom-solid-bold">
            {% for adjustmentStockHeader in adjustmentStockHeaders %}
                <tr>
                    <td class="text-start">{{ adjustmentStockHeader.codeNumber|default }}</td>
                    <td class="text-start">{{ adjustmentStockHeader.transactionDate|default ? adjustmentStockHeader.transactionDate|date('j M Y') }}</td>
                    <td class="text-start">{{ adjustmentStockHeader.adjustmentMode|default }}</td>
                    <td class="text-start">{{ adjustmentStockHeader.warehouse.name|default }}</td>
                    <td class="text-start">{{ adjustmentStockHeader.note|default }}</td>
                </tr>
                <tr class="border-bottom-dotted-bold">
                    <td colspan="5">
                        <table>
                            <tbody>
                                {% if (adjustmentStockHeader.adjustmentMode == 'paper') %}
                                    {% for adjustmentStockPaperDetail in adjustmentStockHeader.adjustmentStockPaperDetails %}
                                        <tr>
                                            <td>{{ adjustmentStockPaperDetail.paper.codeNumber|default }}</td>
                                            <td>{{ adjustmentStockPaperDetail.paper.name|default }}</td>
                                            <td>{{ adjustmentStockPaperDetail.quantityCurrent|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockPaperDetail.quantityAdjustment|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockPaperDetail.quantityDifference|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockPaperDetail.paper.unit.name|default }}</td>
                                            <td>{{ adjustmentStockPaperDetail.memo|default }}</td>
                                        </tr>
                                    {% endfor %}
                                {% elseif (adjustmentStockHeader.adjustmentMode == 'material') %} 
                                    {% for adjustmentStockMaterialDetail in adjustmentStockHeader.adjustmentStockMaterialDetails %}
                                        <tr>
                                            <td>{{ adjustmentStockMaterialDetail.material.code|default }}</td>
                                            <td>{{ adjustmentStockMaterialDetail.material.name|default }}</td>
                                            <td>{{ adjustmentStockMaterialDetail.quantityCurrent|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockMaterialDetail.quantityAdjustment|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockMaterialDetail.quantityDifference|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockPaperDetail.material.unit.name|default }}</td>
                                            <td>{{ adjustmentStockMaterialDetail.memo|default }}</td>
                                        </tr>
                                    {% endfor %}
                                {% elseif (adjustmentStockHeader.adjustmentMode == 'product') %} 
                                    {% for adjustmentStockProductDetail in adjustmentStockHeader.adjustmentStockProductDetails %}
                                        <tr>
                                            <td>{{ adjustmentStockProductDetail.product.code|default }}</td>
                                            <td>{{ adjustmentStockProductDetail.product.name|default }}</td>
                                            <td>{{ adjustmentStockProductDetail.quantityCurrent|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockProductDetail.quantityAdjustment|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockProductDetail.quantityDifference|default|number_format(2) }}</td>
                                            <td>{{ adjustmentStockPaperDetail.product.unit.name|default }}</td>
                                            <td>{{ adjustmentStockProductDetail.memo|default }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %} 
                            </tbody>
                        </table>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="d-print-none">
    <br />
    {{ grid.navigation(form, count, adjustmentStockHeaders) }}
</div>

templates/report/adjustment_stock_header/_list_export.html.twig
<table>
    <thead>
        <tr>
            <th style="text-align: center" colspan="7"><strong>PT. Putracipta Karindomas</strong></th>
        </tr>
        <tr>
            <th style="text-align: center" colspan="7"><strong>Laporan Penyesuaian Stok</strong></th>
        </tr>
        <tr>
            <th style="text-align: center" colspan="7">
                <strong>
                    {% set startDate = form.vars.value.filter.transactionDate.1|default %}
                    {% set endDate = form.vars.value.filter.transactionDate.2|default %}
                    {{ startDate ? startDate|date('j F Y') }} &nbsp;&ndash;&nbsp; {{ endDate ? endDate|date('j F Y') }}
                </strong>
            </th>
        </tr>
        <tr>
            <th colspan="7"></th>
        </tr>
        <tr>
            <th style="text-align: center; width: 100pt"><strong>Penyesuaian #</strong></th>
            <th style="text-align: center; width: 100pt"><strong>Tanggal</strong></th>
            <th style="text-align: center; width: 100pt"><strong>Jenis</strong></th>
            <th style="text-align: center; width: 100pt"><strong>Gudang</strong></th>
            <th style="text-align: center; width: 100pt"><strong>Note</strong></th>
        </tr>
        <tr>
            <th></th>
            <th style="text-align: center"><strong>Kode</strong></th>
            <th style="text-align: center"><strong>Nama Item</strong></th>
            <th style="text-align: center"><strong>Qty Stok</strong></th>
            <th style="text-align: center"><strong>Qty Adjustment</strong></th>
            <th style="text-align: center"><strong>Qty Selisih</strong></th>
            <th style="text-align: center"><strong>Satuan</strong></th>
            <th style="text-align: center"><strong>Memo</strong></th>
        </tr>
        <tr>
            <th colspan="7"></th>
        </tr>
    </thead>
    <tbody>
        {% for adjustmentStockHeader in adjustmentStockHeaders %}
            <tr>
                <td style="text-align: left">{{ adjustmentStockHeader.codeNumber|default }}</td>
                <td style="text-align: left">{{ adjustmentStockHeader.transactionDate|default ? adjustmentStockHeader.transactionDate|date('j M Y') }}</td>
                <td style="text-align: left">{{ adjustmentStockHeader.adjustmentMode|default }}</td>
                <td style="text-align: left">{{ adjustmentStockHeader.warehouse.name|default }}</td>
                <td style="text-align: left">{{ adjustmentStockHeader.note|default }}</td>
            </tr>
            {% if (adjustmentStockHeader.adjustmentMode == 'paper') %}
                {% for adjustmentStockPaperDetail in adjustmentStockHeader.adjustmentStockPaperDetails %}
                    <tr>
                        <td style="text-align: left"></td>
                        <td style="text-align: left">{{ adjustmentStockPaperDetail.paper.codeNumber|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockPaperDetail.paper.name|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockPaperDetail.quantityCurrent|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockPaperDetail.quantityAdjustment|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockPaperDetail.quantityDifference|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockPaperDetail.paper.unit.name|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockPaperDetail.memo|default }}</td>
                    </tr>
                {% endfor %}
            {% elseif (adjustmentStockHeader.adjustmentMode == 'material') %} 
                {% for adjustmentStockMaterialDetail in adjustmentStockHeader.adjustmentStockMaterialDetails %}
                    <tr>
                        <td style="text-align: left"></td>
                        <td style="text-align: left">{{ adjustmentStockMaterialDetail.material.code|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockMaterialDetail.material.name|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockMaterialDetail.quantityCurrent|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockMaterialDetail.quantityAdjustment|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockMaterialDetail.quantityDifference|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockMaterialDetail.material.unit.name|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockMaterialDetail.memo|default }}</td>
                    </tr>
                {% endfor %}
            {% elseif (adjustmentStockHeader.adjustmentMode == 'product') %} 
                {% for adjustmentStockProductDetail in adjustmentStockHeader.adjustmentStockProductDetails %}
                    <tr>
                        <td style="text-align: left"></td>
                        <td style="text-align: left">{{ adjustmentStockProductDetail.product.code|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockProductDetail.product.name|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockProductDetail.quantityCurrent|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockProductDetail.quantityAdjustment|default }}</td>
                        <td style="text-align: center">{{ adjustmentStockProductDetail.quantityDifference|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockProductDetail.product.unit.name|default }}</td>
                        <td style="text-align: left">{{ adjustmentStockProductDetail.memo|default }}</td>
                    </tr>
                {% endfor %}
            {% endif %} 
        {% endfor %}
    </tbody>
</table>